window.ATLAS_ITEMS=[
  {
    "global": 1,
    "id": "thorax-item-001",
    "image": "1.png",
    "section": "COSTELAS",
    "original": "1.",
    "name": "Costelas verdadeiras (1° ao 7° par)",
    "level": 0,
    "group": "",
    "location": "Parede torácica; sete primeiros pares de costelas.",
    "function": "Protegem as vísceras torácicas, sustentam a parede do tórax e participam dos movimentos respiratórios; ligam-se diretamente ao esterno por suas próprias cartilagens costais."
  },
  {
    "global": 2,
    "id": "thorax-item-002",
    "image": "2.png",
    "section": "COSTELAS",
    "original": "2.",
    "name": "Costelas falsas (8° ao 10° par)",
    "level": 0,
    "group": "",
    "location": "Parede torácica inferior; pares 8 a 10.",
    "function": "Contribuem para proteção e mecânica respiratória; suas cartilagens unem-se indiretamente ao esterno por meio da cartilagem da costela superior."
  },
  {
    "global": 3,
    "id": "thorax-item-003",
    "image": "3.png",
    "section": "COSTELAS",
    "original": "3.",
    "name": "Costelas flutuantes (11° e 12° par)",
    "level": 0,
    "group": "",
    "location": "Porção posterolateral inferior da parede torácica.",
    "function": "Protegem a região posterolateral inferior do tórax e permitem mobilidade; não possuem ligação anterior com o esterno."
  },
  {
    "global": 4,
    "id": "thorax-item-004",
    "image": "4.png",
    "section": "COSTELAS",
    "original": "4.",
    "name": "Cartilagem costal",
    "level": 0,
    "group": "",
    "location": "Extremidade anterior das costelas, entre costela e esterno/margem costal.",
    "function": "Prolonga anteriormente a costela, confere elasticidade à parede torácica e participa da expansão e retração durante a respiração."
  },
  {
    "global": 5,
    "id": "thorax-item-005",
    "image": "5.png",
    "section": "COSTELAS",
    "original": "5.",
    "name": "Margem costal",
    "level": 0,
    "group": "",
    "location": "Borda inferior da caixa torácica.",
    "function": "Forma o limite inferior anterior da caixa torácica e serve como importante referência anatômica de superfície."
  },
  {
    "global": 6,
    "id": "thorax-item-006",
    "image": "6.png",
    "section": "COSTELAS",
    "original": "6.",
    "name": "Cabeça da costela",
    "level": 0,
    "group": "",
    "location": "Extremidade posterior da costela, junto às vértebras torácicas.",
    "function": "Articula a costela com os corpos das vértebras torácicas, transmitindo forças e permitindo pequenos movimentos respiratórios."
  },
  {
    "global": 7,
    "id": "thorax-item-007",
    "image": "7.png",
    "section": "COSTELAS",
    "original": "a.",
    "name": "Face articular superior da cabeça da costela",
    "level": 1,
    "group": "",
    "location": "Na cabeça de uma costela típica.",
    "function": "Participa da articulação da cabeça da costela com a vértebra superior correspondente."
  },
  {
    "global": 8,
    "id": "thorax-item-008",
    "image": "8.png",
    "section": "COSTELAS",
    "original": "b.",
    "name": "Face articular inferior da cabeça da costela",
    "level": 1,
    "group": "",
    "location": "Na cabeça de uma costela típica.",
    "function": "Participa da articulação da cabeça da costela com a vértebra de mesmo número."
  },
  {
    "global": 9,
    "id": "thorax-item-009",
    "image": "9.png",
    "section": "COSTELAS",
    "original": "7.",
    "name": "Colo da costela",
    "level": 0,
    "group": "",
    "location": "Entre a cabeça e o tubérculo da costela.",
    "function": "Une a cabeça ao tubérculo da costela e serve de área de fixação para ligamentos costotransversários."
  },
  {
    "global": 10,
    "id": "thorax-item-010",
    "image": "10.png",
    "section": "COSTELAS",
    "original": "8.",
    "name": "Tubérculo da costela",
    "level": 0,
    "group": "",
    "location": "Região posterior, na junção do colo com o corpo.",
    "function": "Articula-se com o processo transverso da vértebra correspondente e serve de inserção ligamentar."
  },
  {
    "global": 11,
    "id": "thorax-item-011",
    "image": "11.png",
    "section": "COSTELAS",
    "original": "9.",
    "name": "Ângulo da costela",
    "level": 0,
    "group": "",
    "location": "Região posterior do corpo da costela, no ponto de maior curvatura.",
    "function": "Marca a região de maior curvatura da costela e relaciona-se com a mudança de direção de seu corpo."
  },
  {
    "global": 12,
    "id": "thorax-item-012",
    "image": "12.png",
    "section": "COSTELAS",
    "original": "10.",
    "name": "Corpo da costela",
    "level": 0,
    "group": "",
    "location": "Porção longa e arqueada da costela.",
    "function": "Constitui a maior parte da costela, formando a parede torácica e contribuindo para proteção e respiração."
  },
  {
    "global": 13,
    "id": "thorax-item-013",
    "image": "13.png",
    "section": "COSTELAS",
    "original": "a.",
    "name": "Sulco da costela",
    "level": 1,
    "group": "",
    "location": "Face interna da margem inferior do corpo da costela.",
    "function": "Abriga e protege o feixe neurovascular intercostal, especialmente veia, artéria e nervo intercostais."
  },
  {
    "global": 14,
    "id": "thorax-item-014",
    "image": "14.png",
    "section": "COSTELAS",
    "original": "11.",
    "name": "Costela I",
    "level": 0,
    "group": "",
    "location": "Abertura superior do tórax, profundamente à clavícula.",
    "function": "Delimita a abertura superior do tórax, protege estruturas cervicotorácicas e oferece inserção a músculos e ligamentos."
  },
  {
    "global": 15,
    "id": "thorax-item-015",
    "image": "15.png",
    "section": "COSTELAS",
    "original": "a.",
    "name": "Sulco da artéria subclávia",
    "level": 1,
    "group": "",
    "location": "Face superior da costela I.",
    "function": "Acomoda a artéria subclávia na face superior da primeira costela, posterior ao tubérculo do escaleno anterior."
  },
  {
    "global": 16,
    "id": "thorax-item-016",
    "image": "16.png",
    "section": "COSTELAS",
    "original": "b.",
    "name": "Tubérculo do músculo escaleno anterior",
    "level": 1,
    "group": "",
    "location": "Face superior da costela I.",
    "function": "Serve de inserção ao músculo escaleno anterior e separa os sulcos da veia e da artéria subclávias."
  },
  {
    "global": 17,
    "id": "thorax-item-017",
    "image": "17.png",
    "section": "COSTELAS",
    "original": "c.",
    "name": "Sulco da veia subclávia",
    "level": 1,
    "group": "",
    "location": "Face superior da costela I.",
    "function": "Acomoda a veia subclávia na face superior da primeira costela, anterior ao tubérculo do escaleno anterior."
  },
  {
    "global": 18,
    "id": "thorax-item-018",
    "image": "18.png",
    "section": "COSTELAS",
    "original": "12.",
    "name": "Costela II",
    "level": 0,
    "group": "",
    "location": "Imediatamente inferior à costela I.",
    "function": "Participa da parede superior do tórax e oferece inserção ao músculo serrátil anterior."
  },
  {
    "global": 19,
    "id": "thorax-item-019",
    "image": "19.png",
    "section": "COSTELAS",
    "original": "a.",
    "name": "Tuberosidade do músculo serrátil anterior",
    "level": 1,
    "group": "",
    "location": "Face superior da costela II.",
    "function": "Serve como área de inserção do músculo serrátil anterior, contribuindo indiretamente para a estabilização e protração da escápula."
  },
  {
    "global": 20,
    "id": "thorax-item-020",
    "image": "20.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "1.",
    "name": "Sincondrose da primeira costela",
    "level": 0,
    "group": "",
    "location": "Entre a primeira cartilagem costal e o manúbrio.",
    "function": "Une firmemente a primeira cartilagem costal ao manúbrio, garantindo estabilidade à parte superior da parede torácica anterior."
  },
  {
    "global": 21,
    "id": "thorax-item-021",
    "image": "21.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "2.",
    "name": "Articulações esternocostais (da segunda à sétima cartilagem costal)",
    "level": 0,
    "group": "",
    "location": "Entre as cartilagens costais 2–7 e o esterno.",
    "function": "Permitem pequenos movimentos entre esterno e cartilagens costais, importantes para a expansão da caixa torácica na respiração."
  },
  {
    "global": 22,
    "id": "thorax-item-022",
    "image": "22.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "a.",
    "name": "Ligamento esternocostal radiado",
    "level": 1,
    "group": "",
    "location": "Face anterior das articulações esternocostais.",
    "function": "Reforça anteriormente as articulações esternocostais e ajuda a estabilizar a união entre cartilagens costais e esterno."
  },
  {
    "global": 23,
    "id": "thorax-item-023",
    "image": "23.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "3.",
    "name": "Articulações costocondrais",
    "level": 0,
    "group": "",
    "location": "Entre costelas e respectivas cartilagens costais.",
    "function": "Unem costela e cartilagem costal, transmitindo movimentos e forças da parede óssea para a porção cartilaginosa."
  },
  {
    "global": 24,
    "id": "thorax-item-024",
    "image": "24.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "4.",
    "name": "Articulações costovertebrais",
    "level": 0,
    "group": "",
    "location": "Região posterior do tórax, entre costelas e vértebras torácicas.",
    "function": "Conectam as costelas às vértebras torácicas e permitem movimentos de elevação e depressão das costelas durante a respiração."
  },
  {
    "global": 25,
    "id": "thorax-item-025",
    "image": "25.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "a.",
    "name": "Articulação da cabeça da costela",
    "level": 1,
    "group": "",
    "location": "Entre a cabeça da costela e os corpos vertebrais adjacentes.",
    "function": "Permite o movimento da cabeça da costela sobre os corpos vertebrais durante a mecânica respiratória."
  },
  {
    "global": 26,
    "id": "thorax-item-026",
    "image": "26.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "i.",
    "name": "Ligamento radiado da cabeça da costela",
    "level": 2,
    "group": "",
    "location": "Face anterior da articulação da cabeça da costela.",
    "function": "Reforça a articulação da cabeça da costela e limita movimentos excessivos."
  },
  {
    "global": 27,
    "id": "thorax-item-027",
    "image": "27.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "b.",
    "name": "Articulação costotransversária",
    "level": 1,
    "group": "",
    "location": "Entre o tubérculo da costela e o processo transverso.",
    "function": "Permite pequenos deslizamentos e rotações entre o tubérculo da costela e o processo transverso durante a respiração."
  },
  {
    "global": 28,
    "id": "thorax-item-028",
    "image": "28.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "i.",
    "name": "Ligamento costotransversário superior",
    "level": 2,
    "group": "",
    "location": "Entre o colo da costela e o processo transverso superior.",
    "function": "Estabiliza a articulação costotransversária e limita deslocamentos excessivos da costela."
  },
  {
    "global": 29,
    "id": "thorax-item-029",
    "image": "29.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "ii.",
    "name": "Ligamento costotransversário lateral",
    "level": 2,
    "group": "",
    "location": "Entre processo transverso e tubérculo da costela.",
    "function": "Reforça lateralmente a articulação costotransversária e contribui para sua estabilidade."
  },
  {
    "global": 30,
    "id": "thorax-item-030",
    "image": "30.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "5.",
    "name": "Ligamento costoxifoideo",
    "level": 0,
    "group": "",
    "location": "Entre cartilagem costal inferior e processo xifoide.",
    "function": "Une a cartilagem da sétima costela ao processo xifoide, reforçando a região inferior da parede torácica anterior."
  },
  {
    "global": 31,
    "id": "thorax-item-031",
    "image": "31.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "6.",
    "name": "Articulações intercondrais",
    "level": 0,
    "group": "",
    "location": "Entre cartilagens costais adjacentes.",
    "function": "Permitem pequenos movimentos entre cartilagens costais adjacentes e aumentam a flexibilidade da margem costal."
  },
  {
    "global": 32,
    "id": "thorax-item-032",
    "image": "32.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "7.",
    "name": "Articulações dos processos articulares (zigapofisárias)",
    "level": 0,
    "group": "",
    "location": "Entre processos articulares de vértebras torácicas adjacentes.",
    "function": "Guiam e limitam os movimentos entre vértebras torácicas, contribuindo para estabilidade e mobilidade controlada da coluna."
  },
  {
    "global": 33,
    "id": "thorax-item-033",
    "image": "33.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "8.",
    "name": "Ligamento longitudinal anterior",
    "level": 0,
    "group": "",
    "location": "Face anterior dos corpos vertebrais.",
    "function": "Limita a hiperextensão da coluna vertebral e reforça anteriormente os corpos e discos vertebrais."
  },
  {
    "global": 34,
    "id": "thorax-item-034",
    "image": "34.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "9.",
    "name": "Ligamento longitudinal posterior",
    "level": 0,
    "group": "",
    "location": "Face posterior dos corpos vertebrais, no canal vertebral.",
    "function": "Limita principalmente a flexão da coluna e reforça posteriormente os corpos vertebrais dentro do canal vertebral."
  },
  {
    "global": 35,
    "id": "thorax-item-035",
    "image": "35.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "10.",
    "name": "Ligamento amarelo",
    "level": 0,
    "group": "",
    "location": "Entre lâminas de vértebras adjacentes.",
    "function": "Une lâminas vertebrais adjacentes, auxilia o retorno da coluna após flexão e limita flexão excessiva."
  },
  {
    "global": 36,
    "id": "thorax-item-036",
    "image": "36.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "11.",
    "name": "Ligamento interespinal",
    "level": 0,
    "group": "",
    "location": "Entre processos espinhosos adjacentes.",
    "function": "Une processos espinhosos adjacentes e limita a flexão excessiva da coluna vertebral."
  },
  {
    "global": 37,
    "id": "thorax-item-037",
    "image": "37.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "12.",
    "name": "Ligamento supra-espinal",
    "level": 0,
    "group": "",
    "location": "Ao longo das extremidades dos processos espinhosos.",
    "function": "Une os ápices dos processos espinhosos e ajuda a limitar a flexão da coluna."
  },
  {
    "global": 38,
    "id": "thorax-item-038",
    "image": "38.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "13.",
    "name": "Ligamento intertransversário",
    "level": 0,
    "group": "",
    "location": "Entre processos transversos adjacentes.",
    "function": "Une processos transversos adjacentes e limita a inclinação lateral contralateral."
  },
  {
    "global": 39,
    "id": "thorax-item-039",
    "image": "39.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "14.",
    "name": "Disco articular",
    "level": 0,
    "group": "",
    "location": "Componente fibrocartilaginoso em articulações relacionadas.",
    "function": "Aumenta a congruência da articulação esternoclavicular, distribui cargas e absorve impactos entre clavícula e esterno."
  },
  {
    "global": 40,
    "id": "thorax-item-040",
    "image": "40.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "15.",
    "name": "Ligamento esternoclavicular anterior",
    "level": 0,
    "group": "",
    "location": "Face anterior da articulação esternoclavicular.",
    "function": "Reforça anteriormente a cápsula esternoclavicular e limita deslocamentos excessivos da clavícula."
  },
  {
    "global": 41,
    "id": "thorax-item-041",
    "image": "41.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "16.",
    "name": "Ligamento esternoclavicular posterior",
    "level": 0,
    "group": "",
    "location": "Face posterior da articulação esternoclavicular.",
    "function": "Reforça posteriormente a cápsula esternoclavicular e contribui para a estabilidade da cintura escapular."
  },
  {
    "global": 42,
    "id": "thorax-item-042",
    "image": "42.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "17.",
    "name": "Ligamento interclavicular",
    "level": 0,
    "group": "",
    "location": "Entre as extremidades esternais das clavículas.",
    "function": "Une as extremidades esternais das clavículas sobre o manúbrio e limita a depressão excessiva da clavícula."
  },
  {
    "global": 43,
    "id": "thorax-item-043",
    "image": "43.png",
    "section": "ARTICULAÇÕES DO TÓRAX",
    "original": "18.",
    "name": "Ligamento costoclavicular",
    "level": 0,
    "group": "",
    "location": "Entre costela I/cartilagem e clavícula.",
    "function": "Ancora a clavícula à primeira costela e limita sua elevação excessiva, estabilizando a articulação esternoclavicular."
  },
  {
    "global": 44,
    "id": "thorax-item-044",
    "image": "44.png",
    "section": "MÚSCULOS DO DORSO",
    "original": "1.",
    "name": "Eretor da espinha",
    "level": 0,
    "group": "",
    "location": "Massa muscular profunda longitudinal do dorso.",
    "function": "Principal extensor da coluna vertebral; também participa da inclinação lateral e da manutenção da postura."
  },
  {
    "global": 45,
    "id": "thorax-item-045",
    "image": "45.png",
    "section": "MÚSCULOS DO DORSO",
    "original": "a.",
    "name": "Espinal do tórax",
    "level": 1,
    "group": "",
    "location": "Porção medial do eretor da espinha na região torácica.",
    "function": "Auxilia na extensão da coluna torácica e na manutenção da postura."
  },
  {
    "global": 46,
    "id": "thorax-item-046",
    "image": "46.png",
    "section": "MÚSCULOS DO DORSO",
    "original": "b.",
    "name": "Longuíssimo do tórax",
    "level": 1,
    "group": "",
    "location": "Porção intermediária do eretor da espinha.",
    "function": "Estende e inclina lateralmente a coluna vertebral e contribui para a estabilização postural."
  },
  {
    "global": 47,
    "id": "thorax-item-047",
    "image": "47.png",
    "section": "MÚSCULOS DO DORSO",
    "original": "",
    "name": "Íliocostal do lombo",
    "level": 1,
    "group": "",
    "location": "Porção lateral do eretor da espinha na região lombar.",
    "function": "Estende e inclina lateralmente a coluna lombar, auxiliando na manutenção da postura."
  },
  {
    "global": 48,
    "id": "thorax-item-048",
    "image": "48.png",
    "section": "MÚSCULOS DO DORSO",
    "original": "2.",
    "name": "Aponeurose do m. eretor da espinha",
    "level": 0,
    "group": "",
    "location": "Região posterior inferior do tronco, relacionada ao eretor da espinha.",
    "function": "Forma uma lâmina tendínea de origem e transmissão de força para o grupo eretor da espinha."
  },
  {
    "global": 49,
    "id": "thorax-item-049",
    "image": "49.png",
    "section": "MÚSCULOS DO DORSO",
    "original": "1.",
    "name": "Semiespinal do tórax",
    "level": 0,
    "group": "",
    "location": "Plano profundo transversoespinal da região torácica.",
    "function": "Estende a coluna torácica bilateralmente e auxilia na rotação contralateral quando atua unilateralmente."
  },
  {
    "global": 50,
    "id": "thorax-item-050",
    "image": "50.png",
    "section": "MÚSCULOS DO DORSO",
    "original": "2.",
    "name": "Multífidos do tórax",
    "level": 0,
    "group": "",
    "location": "Plano profundo ao longo das vértebras torácicas.",
    "function": "Estabilizam as vértebras torácicas e auxiliam na extensão e rotação contralateral da coluna."
  },
  {
    "global": 51,
    "id": "thorax-item-051",
    "image": "51.png",
    "section": "MÚSCULOS DO DORSO",
    "original": "3.",
    "name": "Multífidos do lombo",
    "level": 0,
    "group": "",
    "location": "Plano profundo da região lombar.",
    "function": "Estabilizam as vértebras lombares e participam da extensão e rotação contralateral da coluna."
  },
  {
    "global": 52,
    "id": "thorax-item-052",
    "image": "52.png",
    "section": "MÚSCULOS DO DORSO",
    "original": "4.",
    "name": "Rotadores do tórax",
    "level": 0,
    "group": "",
    "location": "Entre processos transversos e espinhosos torácicos.",
    "function": "Estabilizam segmentos vertebrais torácicos e auxiliam na rotação contralateral e propriocepção."
  },
  {
    "global": 53,
    "id": "thorax-item-053",
    "image": "53.png",
    "section": "MÚSCULOS DO DORSO",
    "original": "5.",
    "name": "Rotadores do lombo",
    "level": 0,
    "group": "",
    "location": "Plano profundo entre elementos vertebrais lombares.",
    "function": "Estabilizam segmentos vertebrais lombares e auxiliam discretamente na rotação e propriocepção."
  },
  {
    "global": 54,
    "id": "thorax-item-054",
    "image": "54.png",
    "section": "MÚSCULOS DO DORSO",
    "original": "6.",
    "name": "Intertransversários do lombo",
    "level": 0,
    "group": "",
    "location": "Entre processos transversos lombares adjacentes.",
    "function": "Estabilizam vértebras lombares e auxiliam na inclinação lateral da coluna."
  },
  {
    "global": 55,
    "id": "thorax-item-055",
    "image": "55.png",
    "section": "MÚSCULOS DO DORSO",
    "original": "7.",
    "name": "Interespinais do tórax",
    "level": 0,
    "group": "",
    "location": "Entre processos espinhosos torácicos adjacentes.",
    "function": "Auxiliam na extensão e estabilização segmentar da coluna torácica."
  },
  {
    "global": 56,
    "id": "thorax-item-056",
    "image": "56.png",
    "section": "MÚSCULOS DO DORSO",
    "original": "8.",
    "name": "Interespinais do lombo",
    "level": 0,
    "group": "",
    "location": "Entre processos espinhosos lombares adjacentes.",
    "function": "Auxiliam na extensão e estabilização segmentar da coluna lombar."
  },
  {
    "global": 57,
    "id": "thorax-item-057",
    "image": "57.png",
    "section": "MÚSCULOS DO DORSO",
    "original": "9.",
    "name": "Levantadores das costelas",
    "level": 0,
    "group": "",
    "location": "Região posterior do tórax, entre processos transversos e costelas.",
    "function": "Elevam as costelas e auxiliam discretamente na inspiração e na inclinação lateral da coluna torácica."
  },
  {
    "global": 58,
    "id": "thorax-item-058",
    "image": "58.png",
    "section": "MAMA",
    "original": "1.",
    "name": "Sulco intermamário",
    "level": 0,
    "group": "",
    "location": "Linha mediana anterior entre as mamas.",
    "function": "Separa superficialmente as duas mamas e constitui referência anatômica da linha mediana anterior."
  },
  {
    "global": 59,
    "id": "thorax-item-059",
    "image": "59.png",
    "section": "MAMA",
    "original": "2.",
    "name": "Sulco inframamário",
    "level": 0,
    "group": "",
    "location": "Dobra inferior entre mama e parede torácica.",
    "function": "Marca a transição inferior da mama para a parede torácica e contribui para o contorno e sustentação da mama."
  },
  {
    "global": 60,
    "id": "thorax-item-060",
    "image": "60.png",
    "section": "MAMA",
    "original": "3.",
    "name": "Estroma da mama (tecido conjuntivo de sustentação)",
    "level": 0,
    "group": "",
    "location": "Tecido conjuntivo de sustentação do corpo da mama.",
    "function": "Sustenta e organiza os componentes glandulares, adiposos, vasculares e nervosos da mama."
  },
  {
    "global": 61,
    "id": "thorax-item-061",
    "image": "61.png",
    "section": "MAMA",
    "original": "4.",
    "name": "Ligamentos suspensores da mama",
    "level": 0,
    "group": "",
    "location": "Bandas fibrosas entre pele e planos profundos da mama.",
    "function": "Fixam a pele e o tecido mamário à fáscia profunda, ajudando a manter a forma e a sustentação da mama."
  },
  {
    "global": 62,
    "id": "thorax-item-062",
    "image": "62.png",
    "section": "MAMA",
    "original": "5.",
    "name": "Corpo da mama (ductos, gordura, vasos e nervos)",
    "level": 0,
    "group": "",
    "location": "Porção principal da mama sobre a parede torácica anterior.",
    "function": "Reúne o parênquima glandular, ductos, gordura, vasos e nervos responsáveis pela estrutura, nutrição, sensibilidade e lactação."
  },
  {
    "global": 63,
    "id": "thorax-item-063",
    "image": "63.png",
    "section": "MAMA",
    "original": "6.",
    "name": "Leito da mama",
    "level": 0,
    "group": "",
    "location": "Plano profundo sobre o qual repousa a mama.",
    "function": "Serve como base de apoio da mama sobre a parede torácica, principalmente sobre a fáscia dos músculos peitoral maior e serrátil anterior."
  },
  {
    "global": 64,
    "id": "thorax-item-064",
    "image": "64.png",
    "section": "MAMA",
    "original": "7.",
    "name": "Espaço retromamário",
    "level": 0,
    "group": "",
    "location": "Entre corpo da mama e fáscia peitoral.",
    "function": "Permite certo grau de mobilidade da mama sobre a fáscia peitoral por conter tecido conjuntivo frouxo."
  },
  {
    "global": 65,
    "id": "thorax-item-065",
    "image": "65.png",
    "section": "MAMA",
    "original": "8.",
    "name": "Aréola da mama",
    "level": 0,
    "group": "",
    "location": "Área pigmentada ao redor da papila.",
    "function": "Área pigmentada que circunda a papila e contém glândulas especializadas que ajudam a proteger e lubrificar a pele durante a amamentação."
  },
  {
    "global": 66,
    "id": "thorax-item-066",
    "image": "66.png",
    "section": "MAMA",
    "original": "9.",
    "name": "Papila mamária",
    "level": 0,
    "group": "",
    "location": "Centro da aréola.",
    "function": "É a projeção onde desembocam os ductos lactíferos, permitindo a saída do leite durante a lactação."
  },
  {
    "global": 67,
    "id": "thorax-item-067",
    "image": "67.png",
    "section": "MAMA",
    "original": "10.",
    "name": "Glândulas areolares",
    "level": 0,
    "group": "",
    "location": "Na aréola.",
    "function": "Secretam material lipídico que lubrifica e protege a aréola e a papila, especialmente durante a amamentação."
  },
  {
    "global": 68,
    "id": "thorax-item-068",
    "image": "68.png",
    "section": "MAMA",
    "original": "11.",
    "name": "Processo axilar da mama",
    "level": 0,
    "group": "",
    "location": "Prolongamento superolateral em direção à axila.",
    "function": "Prolonga o tecido mamário em direção à axila e é clinicamente relevante na avaliação de alterações mamárias e linfonodais."
  },
  {
    "global": 69,
    "id": "thorax-item-069",
    "image": "69.png",
    "section": "MAMA",
    "original": "12.",
    "name": "Lóbulos da mama",
    "level": 0,
    "group": "",
    "location": "No parênquima glandular mamário.",
    "function": "Unidades glandulares que contêm lóbulos menores e alvéolos secretores responsáveis pela produção de leite na lactação."
  },
  {
    "global": 70,
    "id": "thorax-item-070",
    "image": "70.png",
    "section": "MAMA",
    "original": "13.",
    "name": "Ductos lactíferos",
    "level": 0,
    "group": "",
    "location": "Do tecido glandular em direção à papila.",
    "function": "Conduzem o leite dos lóbulos glandulares em direção à papila mamária."
  },
  {
    "global": 71,
    "id": "thorax-item-071",
    "image": "71.png",
    "section": "MAMA",
    "original": "14.",
    "name": "Seios Lactíferos",
    "level": 0,
    "group": "",
    "location": "Porção dilatada dos ductos próxima à papila.",
    "function": "Regiões dilatadas dos ductos lactíferos próximas à papila, tradicionalmente descritas como áreas de armazenamento temporário do leite."
  },
  {
    "global": 72,
    "id": "thorax-item-072",
    "image": "72.png",
    "section": "MAMA",
    "original": "15.",
    "name": "a. axilar",
    "level": 0,
    "group": "",
    "location": "Axila.",
    "function": "Principal artéria da axila; origina ramos que participam da irrigação da parede torácica e da porção lateral da mama."
  },
  {
    "global": 73,
    "id": "thorax-item-073",
    "image": "73.png",
    "section": "MAMA",
    "original": "16.",
    "name": "a. Torácica lateral",
    "level": 0,
    "group": "",
    "location": "Parede torácica lateral, ramo da artéria axilar.",
    "function": "Irriga a parede torácica lateral e fornece importante suprimento arterial para a porção lateral da mama."
  },
  {
    "global": 74,
    "id": "thorax-item-074",
    "image": "74.png",
    "section": "MAMA",
    "original": "a.",
    "name": "Ramos mamários laterais",
    "level": 1,
    "group": "",
    "location": "Porção lateral da mama.",
    "function": "Distribuem sangue arterial para a porção lateral da mama."
  },
  {
    "global": 75,
    "id": "thorax-item-075",
    "image": "75.png",
    "section": "MAMA",
    "original": "17.",
    "name": "a. Subclávia",
    "level": 0,
    "group": "",
    "location": "Raiz do pescoço e abertura superior do tórax.",
    "function": "Fornece origem indireta a vasos que irrigam a mama, especialmente por meio da artéria torácica interna e do tronco toracoacromial."
  },
  {
    "global": 76,
    "id": "thorax-item-076",
    "image": "76.png",
    "section": "MAMA",
    "original": "18.",
    "name": "a. Torácica interna",
    "level": 0,
    "group": "",
    "location": "Face interna da parede torácica anterior, paralela ao esterno.",
    "function": "Fornece ramos perfurantes e intercostais anteriores que irrigam sobretudo a porção medial da mama."
  },
  {
    "global": 77,
    "id": "thorax-item-077",
    "image": "77.png",
    "section": "MAMA",
    "original": "a.",
    "name": "Ramos mamários laterais",
    "level": 1,
    "group": "",
    "location": "Ramos destinados à mama.",
    "function": "Participam do suprimento arterial do tecido mamário conforme a distribuição dos ramos que alcançam a mama."
  },
  {
    "global": 78,
    "id": "thorax-item-078",
    "image": "78.png",
    "section": "MAMA",
    "original": "19)",
    "name": "a. Intercostais posteriores",
    "level": 0,
    "group": "",
    "location": "Espaços intercostais posteriores.",
    "function": "Fornecem ramos para espaços intercostais e ramos cutâneos laterais que contribuem para a irrigação da mama."
  },
  {
    "global": 79,
    "id": "thorax-item-079",
    "image": "79.png",
    "section": "MAMA",
    "original": "a.",
    "name": "Ramos cutâneos laterais",
    "level": 1,
    "group": "",
    "location": "Parede torácica lateral.",
    "function": "Irrigam pele e tecidos da parede torácica lateral e contribuem para a vascularização lateral da mama."
  },
  {
    "global": 80,
    "id": "thorax-item-080",
    "image": "80.png",
    "section": "MAMA",
    "original": "b.",
    "name": "Ramos mamários laterais",
    "level": 1,
    "group": "",
    "location": "Porção lateral da mama.",
    "function": "Contribuem para o suprimento arterial do tecido mamário lateral."
  },
  {
    "global": 81,
    "id": "thorax-item-081",
    "image": "81.png",
    "section": "MAMA",
    "original": "20)",
    "name": "vv. Mamárias laterais",
    "level": 0,
    "group": "",
    "location": "Porção lateral da mama.",
    "function": "Drenam o sangue venoso da porção lateral da mama em direção às veias torácicas laterais e ao sistema axilar."
  },
  {
    "global": 82,
    "id": "thorax-item-082",
    "image": "82.png",
    "section": "MAMA",
    "original": "21)",
    "name": "vv. Torácicas laterais",
    "level": 0,
    "group": "",
    "location": "Parede torácica lateral e axila.",
    "function": "Drenam a parede torácica lateral e a mama para a veia axilar."
  },
  {
    "global": 83,
    "id": "thorax-item-083",
    "image": "83.png",
    "section": "MAMA",
    "original": "22)",
    "name": "v. Axilar",
    "level": 0,
    "group": "",
    "location": "Axila.",
    "function": "Recebe grande parte da drenagem venosa lateral da mama e a conduz para a veia subclávia."
  },
  {
    "global": 84,
    "id": "thorax-item-084",
    "image": "84.png",
    "section": "MAMA",
    "original": "23)",
    "name": "vv. Mamárias mediais",
    "level": 0,
    "group": "",
    "location": "Porção medial da mama.",
    "function": "Drenam a porção medial da mama para as veias torácicas internas."
  },
  {
    "global": 85,
    "id": "thorax-item-085",
    "image": "85.png",
    "section": "MAMA",
    "original": "24)",
    "name": "vv. Torácicas internas",
    "level": 0,
    "group": "",
    "location": "Face interna da parede torácica anterior.",
    "function": "Recebem veias da parede torácica anterior e da mama, drenando superiormente para o sistema braquiocefálico."
  },
  {
    "global": 86,
    "id": "thorax-item-086",
    "image": "86.png",
    "section": "MAMA",
    "original": "25)",
    "name": "v. Subclávia",
    "level": 0,
    "group": "",
    "location": "Posterior à clavícula.",
    "function": "Recebe a veia axilar e conduz o sangue venoso do membro superior e de parte da parede torácica para a veia braquiocefálica."
  },
  {
    "global": 87,
    "id": "thorax-item-087",
    "image": "87.png",
    "section": "MAMA",
    "original": "26)",
    "name": "vv. Intercostais anteriores",
    "level": 0,
    "group": "",
    "location": "Espaços intercostais anteriores.",
    "function": "Drenam os espaços intercostais anteriores e comunicam-se com as veias torácicas internas."
  },
  {
    "global": 88,
    "id": "thorax-item-088",
    "image": "88.png",
    "section": "MAMA",
    "original": "27)",
    "name": "vv. Intercostais posteriores",
    "level": 0,
    "group": "",
    "location": "Espaços intercostais posteriores.",
    "function": "Drenam os espaços intercostais posteriores para o sistema ázigo e estabelecem comunicações com plexos venosos vertebrais."
  },
  {
    "global": 89,
    "id": "thorax-item-089",
    "image": "89.png",
    "section": "MAMA",
    "original": "28)",
    "name": "Plexos venosos vertebrais",
    "level": 0,
    "group": "",
    "location": "Ao redor e no interior da coluna vertebral.",
    "function": "Formam redes venosas sem válvulas ao redor da coluna, permitindo comunicação entre sistemas venosos torácicos, vertebrais e intracranianos."
  },
  {
    "global": 90,
    "id": "thorax-item-090",
    "image": "90.png",
    "section": "MAMA",
    "original": "29)",
    "name": "Sistema ázigo",
    "level": 0,
    "group": "",
    "location": "Mediastino posterior, junto à coluna vertebral.",
    "function": "Drena a parede posterior do tórax e conduz sangue venoso para a veia cava superior."
  },
  {
    "global": 91,
    "id": "thorax-item-091",
    "image": "91.png",
    "section": "MAMA",
    "original": "30)",
    "name": "nn. Supraclaviculares",
    "level": 0,
    "group": "",
    "location": "Região supraclavicular e parede torácica superior.",
    "function": "Fornecem sensibilidade cutânea à região superior da mama e parede torácica acima, especialmente derivados dos ramos C3–C4 do plexo cervical."
  },
  {
    "global": 92,
    "id": "thorax-item-092",
    "image": "92.png",
    "section": "MAMA",
    "original": "31)",
    "name": "Ramos cutâneos mediais dos nn. intercostais anteriores",
    "level": 0,
    "group": "",
    "location": "Porção anterior e medial da parede torácica.",
    "function": "Fornecem sensibilidade cutânea à porção medial da mama e da parede torácica anterior."
  },
  {
    "global": 93,
    "id": "thorax-item-093",
    "image": "93.png",
    "section": "MAMA",
    "original": "32)",
    "name": "Ramos cutâneos laterais dos nn. intercostais posteriores",
    "level": 0,
    "group": "",
    "location": "Porção lateral da parede torácica.",
    "function": "Fornecem sensibilidade cutânea à porção lateral da mama e da parede torácica."
  },
  {
    "global": 94,
    "id": "thorax-item-094",
    "image": "94.png",
    "section": "MAMA",
    "original": "33)",
    "name": "Explique a drenagem linfática das mamas",
    "level": 0,
    "group": "",
    "location": "Mama e cadeias linfonodais relacionadas.",
    "function": "A maior parte da linfa, especialmente dos quadrantes laterais, segue para linfonodos axilares, sobretudo o grupo peitoral; a porção medial drena também para linfonodos paraesternais, podendo comunicar-se com a mama contralateral. Há ainda vias para linfonodos intercostais posteriores e inferiores. A drenagem linfática é fundamental para defesa imune e para compreender a disseminação de neoplasias mamárias."
  }
];
